- name: install python
  hosts: local
  vars:
    container_name: my_container
  tasks: 
    - name: Install Python3 and pip in the container
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: /bin/sh -c "apt update && apt install -y python3 python3-pip"

    - name: Execute a Python command in the container
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: python3 -c "print('Hello World')"
      register: hello_world_output

    - name: Print Hello World output
      debug:
        msg: "{{ hello_world_output.stdout }}"
