name: Infrastructure Setup and Configuration
on:
    push:
        branches:
            - main
        paths:
            - 'terraform/**'
            - 'ansible/**'
            - '.github/workflows/infra_setup_config.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'terraform/**'
            - 'ansible/**'
            - '.github/workflows/infra_setup_config.yml'
    workflow_dispatch: # Allows manual triggering of the workflow
jobs:
    setup_infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.0.0

            - name: Initialize Terraform
              run: terraform init

            - name: Apply Terraform Configuration
              run: terraform apply -auto-approve

            - name: Set up Ansible
              uses: dawidd6/action-ansible-playbook@v3
              with:
                  ansible_version: 2.9.10

            - name: Run Ansible Playbook
              run: ansible-playbook -i inventory setup.yml